#!/usr/bin/env bash
# domain information

# displaying info
display_info () {
    result=$(dig +short "$1")
    if [ -z "$result" ]; then
        echo "No record found for $1"
    else
        echo "The subdomain $2 points to $result"
    fi
}

# provisions check
if [ "$#" -eq 2 ]; then
    display_info "$2.$1" "$2"
else
    display_info "www.$1" "www"
    display_info "lb-01.$1" "lb-01"
    display_info "web-01.$1" "web-01"
    display_info "web-02.$1" "web-02"
fi
