#!/usr/bin/env bash
# displaying domain info

# displayin info
display_info () {
    result=$(dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n1)
    record_type=$(echo "$result" | awk '{print $4}')
    destination=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $destination"
}
# ..
if [ "$#" -eq 2 ]; then
    display_info "$2.$1" "$2"
else
    display_info "www.$1" "www"
    display_info "lb-01.$1" "lb-01"
    display_info "web-01.$1" "web-01"
    display_info "web-02.$1" "web-02"
fi
