#!/usr/bin/env bash
# script displaying information about domains

# Function
get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    # Query DNS records.
    local dns_info
    dns_info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print}')

    # Parse the DNS info
    local record_type
    record_type=$(echo "$dns_info" | awk '{print $4}')
    local destination
    destination=$(echo "$dns_info" | awk '{print $5}')

    # information output
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# script
domain="$1"
subdomain="$2"

# displaying information
if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    # Display info.
    get_subdomain_info "$domain" "$subdomain"
fi
