#!/usr/bin/env bash
# script transfering a file from our client to server.

PATH_TO_FILE=$1;
IP=$2;
USERNAME=$3;
PATH_TO_SSH_KEY=$4;

if [ "$#" -ne 4 ]; 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
