#!/usr/bin/env bash
# Installing Nginx
sudo apt -y install nginx

# custom 404 error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Modify Nginx
sudo sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Restart Nginx.
sudo service nginx restart

# Enable 'Nginx http'
sudo ufw allow 'Nginx HTTP'
