#!/usr/bin/env bash
# Installing Nginx.

# Update upgrade packages
apt-get update
apt-get upgrade -y
apt-get install -y nginx

# Creating directories and files,.
mkdir -p /var/www/html
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx.
cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      internal;
    }
}
EOF

# Restarting
service nginx restart

