#!/usr/bin/env bash
# 0-custom_http_response_header configuring brrad
# new ubuntu machine

# Updating package info
sudo apt-get -y update

# Nginx installation
sudo apt-get -y install nginx

# HTML files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Nginx configuration
new_config="add_header X-Served-By \$hostname;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\tinternal;\n\t}\n"

# Updating Nginx configuration
sudo sed -i "/server_name _;/c\\$new_config" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
