#!/usr/bin/env bash
# installing and configuring HAProxy on lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# editing configuration file.
server_config=\
"
frontend  cobby-frontend
        bind *:80
        mode http
        default_backend cobby-backend
backend cobby-backend
        balance roundrobin
        server 434802-web-01 100.27.4.8:80 check
        server 434802-web-02 18.207.1.51:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy.
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
