#!/usr/bin/env bash
# Script to ping IP address passed inform of an argument
# It accepts string as an argument
# And also pings an IP address passed as argument 5 times

if [ "$#" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
