#!/usr/bin/env bash
# Displaying "To infinity and beyond" indefinitely
#   Displaying I am invincible!!! in between each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
