#!/usr/bin/env bash
# displaying Best School 10 times, but for 9th iteration, display Best School and then Hi on a new line.
count=0
while [ $count -lt 10 ]
do 
if [ $count -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
((count++))
done
