#!/usr/bin/env bash
# displaying time for 12 hours and 59 minutes
#   Displaying hours from 0 to 12.
#   Displaying minutes from 1 to 59.

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
