#!/usr/bin/env bash
# A script to configure an Ubuntu server with the requirements stated below
# changes the following domain resolve ips
# ----  localhost from 127.0.0.1 to 127.0.0.2
# ---- facebook.com from 157.240.11.35 to 8.8.8.8

cp /etc/hosts ~/hosts.new
# Configures localhost to resolve to 127.0.0.2
# sed -i s/^127.0.0.2/127.0.0.1/ ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
# Configures the facebook.com to resolve to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
